server:
  port: 9000

spring:
  application:
    name: "reports"
  profiles:
    active: "development"
  config:
    import: "optional:configserver:http://localhost:8080"

  datasource:
    url: jdbc:mysql://localhost:5432/reportsdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop

