server:
  port: 9000

spring:
  application:
    name: "reports"
  profiles:
    active: "development"
  config:
    import: "optional:configserver:http://localhost:8071"

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true